spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password:
  thymeleaf:
    cache: false
currency:
  access-key: ee50cd7cc73c9b7a7bb3d9617cfb6b9c 22
  url: http://www.apilayer.net/api/live
  source: USD
  currencies: KRW,JPY,PHP